install.packages("ggplot2")
install.packages("igraph")
install.packages("ggfortify")
install.packages("ape")
library(ggplot2)
library(ggfortify)
library(igraph)
library(ape)
source("functions.R")
install.packages("GenABEL.data", repos="http://R-Forge.R-project.org")
install.packages("./GenABEL_1.8-0.tar.gz", repos = NULL, type = "source")
